### PR TITLE
Fix missing import + Merge CSS to single file

### PR DESCRIPTION
**Pull request by thhomas**
The PR fixes a missing replacement of ol.Overlay with an import of ol/overlay in synchronizeinteraction.js.
I also included a merge of all CSS files to one single file as it is done in openlayers. It is more convenient to include this single file when using ol-ext than including all separate files.

### CODE REVIEW

**Comment by Viglino** [comment]
Not sure its a good idea to merge all css. 
This can be done with a script as it is in the distribution on ol-ext (https://github.com/Viglino/ol-ext/blob/gh-pages/dist/ol-ext.css).

**Comment by Viglino** [comment]
@darkscript I've started to write a gulp script to recreate the current dist with your modification.
I'll try to push it this week-end 😃

**Comment by darkscript** [comment]
@thhomas Personally I would prefer to work with the single css per module, if need be, @Viglino can do a gulp to merge the css and one can choose to use the individual css or use the global(merged) css, what do you think?

**Comment by thhomas** [comment]
Ok, it is even better to have both options.

**Pull request closed without merging**
